name: .NET Build Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore
      - name: Run Auto Test Script
        shell: powershell
        run: |
          Write-Host "Searching for solution file..."
          $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1

          if (-not $sln) {
              Write-Host "No solution file found"
              exit 1
          }

          Write-Host " Restoring..."
          dotnet restore $sln.FullName
          if ($LASTEXITCODE -ne 0) { exit 1 }

          Write-Host " Building..."
          dotnet build $sln.FullName --configuration Release --no-restore
          if ($LASTEXITCODE -ne 0) { exit 1 }

          Write-Host " Searching test projects..."
          $tests = Get-ChildItem -Recurse -Filter *.csproj | Where-Object {
              $_.Name -like "*Test*" -or $_.Name -like "*Tests*"
          }

          if ($tests.Count -eq 0) {
              Write-Host "No test projects found"
              exit 0
          }

          foreach ($test in $tests) {
              Write-Host "Running tests: $($test.Name)"
              dotnet test $test.FullName --configuration Release --no-build --verbosity normal

              if ($LASTEXITCODE -ne 0) {
                  Write-Host "Test Failed"
                  exit 1
              }
          }

          Write-Host " All tests passed"

  publish:
    runs-on: self-hosted
    needs: build

    environment: production

    env:
      BUILD_CONFIGURATION: Release
      PUBLISH_DIR: C:\publish-temp

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Project Files
        run: Get-ChildItem -Recurse -Filter *.csproj


  deploy:
    runs-on: self-hosted
    needs: publish

    env:
      BUILD_CONFIGURATION: Release
      PUBLISH_DIR: C:\publish-temp

    steps:
      - name: Stop App Pool
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "DefaultAppPool"

      - name: Publish Project
        run: |
          $proj = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1
          dotnet publish $proj.FullName -c ${{ env.BUILD_CONFIGURATION }} -o ${{ env.PUBLISH_DIR }} 
      - name: Clean IIS Folder
        run: |
          Remove-Item "C:\inetpub\TestingApp\*" -Recurse -Force
      - name: Copy Files to IIS   # 🔥 MISSING STEP
        run: |
          xcopy /E /I /Y "C:\publish-temp\*" "C:\inetpub\TestingApp\"

      - name: Start App Pool
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "DefaultAppPool"

      - name: Restart IIS
        run: iisreset